export interface OrderManualClose {
  po: string;
  pur_NO: string;
  batch: string;
  confirm_Type: string;
  pur_Date: string | null;
  factory_Code: string;
  supplier_NO: string;
  supplier_Name: string;
  subcon_Desc: string;
  art: string;
  model_NO: string;
  model_Name: string;
  lean: string;
  unit: string;
  t1_CRD: string | null;
  t1_Request_Date: string | null;
  t1_RTD: string | null;
  t2_Confirm_Delivery_Date: string | null;
  kind: string;
  working_Start_Date: string | null;
  working_Category: string;
  t2Mtl_No: string;
  t2Mtl_Name: string;
  initial_Working_Start_Date: string | null;
  t1Mtl_No: string;
  t1Mtl_Name: string;
  tool_No: string;
  tool_Class: string;
  qty: number;
  batch_Qty: number;
  created_By: string;
  upload_Time: string | null;
  status: string;
  forming_Date: string | null;
  confirm_Turnover_Date: string | null;
  t2PPA: string;
  pendingPairs: number;
  usingPairs: number;
  monthQty: number;
}
