import { MOULD } from "./mould";
export interface DATA_MD_ORDER_DETAIL {
    tOrder_ID: string;
    tOrder_NO: string;
    create_Category: string;
    create_Supplier_ID: string;
    req_Category: string;
    req_Supplier_ID: string;
    req_Category_2: string;
    req_Supplier_ID_2: string;
    pur_NO: string;
    tool_No: string;
    tool_Class: string;
    manuf_Supplier_ID: string;
    pay_Category: string;
    pay_Supplier_ID: string;
    admin_Category: string;
    admin_Supplier_ID: string;
    reason: string;
    technician: string;
    exp_Stock_Supplier_ID: string;
    create_Time: string | null;
    created_By: string;
    update_Time: string | null;
    updated_By: string;
    station: string;
    //
    reason_Lang: string;
    applier: string;
    applier_CN: string;
    applier_EN: string;
    applier_LC: string;
    request_Category: string;
    request_Category_CN: string;
    request_Category_EN: string;
    request_Category_LC: string;
    request_Category_2: string;
    request_Category_2_CN: string;
    request_Category_2_EN: string;
    request_Category_2_LC: string;
    tool_Class_Tool_Type: string;
    stock_Category: string;
    stock_Supplier_ID: string;
    mould_Supplier_No: string;
    mould_Supplier_Name: string;
    mould_Supplier_Name_CN: string;
    mould_Supplier_Name_EN: string;
    mould_Supplier_Name_LC: string;
    list_Mould: MOULD[];
    list_Mould_Total: MOULD[];
}