export interface TB_SSB_T2_ORDER {
  id: string;
  feedBackType?: string;
  totalProductionQty?: number;
  production_Time?: string | null;
  po: string;
  pur_NO: string;
  batch: string;
  pur_Class: string;
  confirm_Type: string;
  confirm_Type_check: string;
  pur_Date: string | null;
  factory_Code: string;
  supplier_NO: string;
  supplier_Name: string;
  subcon_Desc: string;
  art: string;
  model_NO: string;
  model_Name: string;
  lean: string;
  unit: string;
  t1_CRD: string | null;
  cust_CRD: string | null;
  t1_Request_Date: string | null;
  pO_Release_Date: string | null;
  t1_RTD: string | null;
  t2_Exp_Delivery_Date: string | Date;
  t2_Exp_Delivery_Date_Check?: string;
  t2_Exp_Delivery_Datetime?: Date;
  t2_Confirm_Delivery_Date: string | Date;
  kind: string;
  part: string;
  partName: string;
  ex_Part: string;
  ex_PartName: string;
  is_Closed: boolean;
  close_Comment: string;
  working_Start_Date: string | null;
  working_Category: string;
  transfer_Date: string | null;
  t2Mtl_No: string;
  t2Mtl_Name: string;
  initial_Working_Start_Date: string | null;
  t1Mtl_No: string;
  t1Mtl_Name: string;
  tool_No: string;
  tool_Class: string;
  qty: number;
  batch_Qty: number;
  created_By: string;
  create_Time: string | null;
  upload_Time: string | null;
  station: string;
  status: string;
  forming_Date: string | null;
  confirm_Turnover_Date: string | Date;
  t2PPA: string;
  pendingPairs: number;
  usingPairs: number;
  monthQty: number;
  isCheck?: boolean;
  isEnable?: boolean;
}

export interface TB_SSB_T2_ORDER_EDIT {
  po: string;
  pur_NO: string;
  batch: string;
  pur_Class: string;
  confirm_Type: string;
  pur_Date: string | null;
  factory_Code: string;
  supplier_NO: string;
  supplier_Name: string;
  subcon_Desc: string;
  art: string;
  model_NO: string;
  model_Name: string;
  lean: string;
  unit: string;
  t1_CRD: string | null;
  cust_CRD: string | null;
  t1_Request_Date: string | null;
  pO_Release_Date: string | null;
  t1_RTD: string | null;
  //-------------------->
  t2_Exp_Delivery_Date: string;
  t2_Confirm_Delivery_Date: string | null;
  kind: string;
  part: string;
  partName: string;
  ex_Part: string;
  ex_PartName: string;
  is_Closed: boolean;
  close_Comment: string;
  working_Start_Date: string | null;
  working_Category: string;
  transfer_Date: string | null;
  t2Mtl_No: string;
  t2Mtl_Name: string;
  initial_Working_Start_Date: string | null;
  t1Mtl_No: string;
  t1Mtl_Name: string;
  tool_No: string;
  tool_Class: string;
  qty: number;
  batch_Qty: number;
  created_By: string;
  create_Time: string | null;
  upload_Time: string | null;
  station: string;
  status: string;
  forming_Date: string | null;
  confirm_Turnover_Date: string | null;
  t2PPA: string;
  pendingPairs: number;
  usingPairs: number;
  monthQty: number;
}