export interface TB_SSB_T2_MD_ORDER_Confirm {
    tOrder_ID: string;
    tOrder_NO: string;
    create_Category: string;
    create_Supplier_ID: string;
    req_Category: string;
    req_Supplier_ID: string;
    req_Category_2: string;
    req_Supplier_ID_2: string;
    pur_NO: string;
    tool_No: string;
    tool_Class: string;
    manuf_Supplier_ID: string;
    pay_Category: string;
    pay_Supplier_ID: string;
    admin_Category: string;
    admin_Supplier_ID: string;
    reason: string;
    technician: string;
    exp_Stock_Supplier_ID: string;
    create_Time: string | null;
    created_By: string;
    update_Time: string | null;
    updated_By: string;
    station: string;
    tool_Name: string;
    supplier_CNName: string;
    supplier_LCName: string;
    supplier_ENName: string;
    pay_Supplier_Name: string;
    pay_Supplier_No: string;
    request_Date: string | null;
    tool_Class_Name: string;
    supplier_NO: string;
    req_Supplier_No: string;
    manufSupplierNO: string;
    manufSupplierName: string;
    createSupplierNO: string;
    adminSupplierNO: string;
    exp_Delivery_Date: string | null;
    stock_Supplier_NO: string;
    exp_Release_Date: string | null;
    stock_Supplier_ID: string;
    mould_ID: string;
    factory_Code: string;
    stock_Factory_Code: string;
    size_From: string;
    size_End: string;
    qty: number | null;
}